<?php if ($pageCount): ?>
<nav>
    <ul class="pagination">
        <!-- previous page links -->
        <?php if (isset($previous)): ?>
            <li>
                <a href="<?php echo $this->url($route, array('page' => $previous)); ?>" aria-label="Previous">
                  &lt; Previous
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <a href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach($pagesInRange as $page) : ?>
            <?php if ($page != $current) : ?>
                <li>
                    <a href="<?php echo $this->url($route, array('page' => $page)); ?>">
                      <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                  <a href="#">
                    <?php echo $page; ?>
                  </a>
                </li>
            <?php endif;?>
        <?php endforeach;?>

        <!-- Next page link -->
        <?php if (isset($next)) : ?>
            <li>
                <a href="<?php echo $this->url($route, array('page' => $next));?>" arial-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        <?php else: ?>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
