<h1>Add Blog Post</h1>
<?php
    /** @var \Zend\Form\Form $form */
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>
  <div>
    <?php echo $this->formRow($form->get('slug')); ?>
</div>
<div>
    <?php echo $this->formRow($form->get('content')); ?>
</div>
<div>
    <?php echo $this->formRow($form->get('category')); ?>
</div>
  <div>
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>
