<h1><?php echo $this->translate('Posts'); ?></h1>

<?php if (!empty($paginator)): ?>
    <?php foreach($paginator as $post): ?>
        <?php
            $postedAt = $this->dateFormat(
                    $post->getCreated(),
                    IntDateFormatter::MEDIUM, // Date
                    IntDateFormatter::MEDIUM, // Time
                    'en_US'
                );
        ?>
        <h2>
          <a href="<?php echo $this->url('display-root', array('categorySlug' => $post->getCategory()->getSlug(), 'postSlug' => $post->getSlug())); ?>">
            <?php echo $this->escapeHtml($post->getTitle()); ?>
          </a>
        </h2>
        <br />
        <?php echo sprintf($this->translate('Posted on %s in the %s category', $postedAt, $this->escapeHtml($post->getCategory()->getName()))); ?>
        <?php /** @var \Blog\Entity\Post $post */?>
            <strong>ID:</strong> <?php echo $this->escapeHtml($post->getId()); ?>
            <br/>
            <strong>Title:</strong> <?php echo $this->escapeHtml($post->getTitle()); ?>
            <br />
            <strong>Category:</strong><?php echo $this->escapeHtml($post->getCategory()->getName()); ?>
            <br/>
            <strong>Content:</strong>
            <br />
            <?php echo nl2br($this->escapeHtml($post->getContent()));?>
            <hr/>
    <?php endforeach; ?>
    <?php echo $this->paginationControl($paginator,
            'Sliding', //scrolling style
            'partial/pagination', //
            array('route' => 'blog/paged')); ?>

<?php else: ?>
    <p><?php echo $this->translate('There are currently no posts.'); ?></p>
<?php endif; ?>
