<h1>Add User</h1>

<?php 
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>


<div class="form-group">
    <?php echo $this->formRow($form->get('first_name'));?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('last_name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group"> 
    <?php echo $this->formRow($form->get('password'));?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('repeat_password')); ?>
</div>
<div class="form-group">
    <?php echo $this->formSubmit($form->get('submit')); ?>  
</div>    

<?php echo $this->form()->closeTag(); ?>

      