<h1>Login Page</h1>
<?php 
/** @var $form \User\Form\Login */
    $form = $this->form;
    $form->prepare();    
    echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?php echo $this->formRow($form->get('email')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>
<div class="form-group">
    <?php echo $this->formSubmit($form->get('submit'));?>
</div>
<?php $this->form()->closeTag(); ?>